### ISSUE TITLE
gen_to_unit incompatible with multiprocessing

### ISSUE THREAD

**Issue by cboulay** [ezmsg-org/ezmsg#85]
>   File "/Users/me/mambaforge/envs/ez/lib/python3.11/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'abc.DummyUnit'>: attribute lookup DummyUnit on abc failed

But it works fine if I fully define `DummySettings(ez.Settings)` and `Dummy(Gen)`.

I tried providing the `__module__` on the dynamic type defined at the bottom of the `gen_to_unit` method...

```Python
        type(
            f"{func.__name__.capitalize()}Unit",
            (ez.Unit,),
            {
                ...,
                "__module__": getmodule(func),
                ...
            },
        ),
```

This gets past the first error and might be a good idea anyway, but a different error remains:

>_pickle.PicklingError: Can't pickle <class 'DummyUnit'>: import of module <module 'ezmsg.chad.dummy' from '/Users/me/Code/tmp/ezmsg/ezmsg-chad/src/ezmsg/chad/dummy.py'> failed

Apparently we also (or only) need to provide `__reduce__`. [Relevant SO answer](https://stackoverflow.com/a/11770528).

**Comment by cboulay** [comment]
I pip installed [`multiprocess`](https://github.com/uqfoundation/multiprocess) which is supposed to be identical to `multiprocessing` except it uses `dill` instead of `pickle`. Then I modified the import statements in `ezmsg.core.backendprocess` to use `multiprocess` instead of `multiprocessing`. This works!

I don't know if this is the right solution for this project though.

**Comment by griffinmilsap** [comment]
Can verify this is still an issue.  Maybe best path forward is to add `multiprocess` to optional dependencies and use it if installed.  We can add an environment variable to force use of stdlib multiprocessing if `multiprocess` is installed by some other module

**Comment by cboulay** [comment]
I think this is now obsolete given the approach we intend to take in #158
